#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Olidol\Console\Command;
use Olidol\Container;

$container = new Container();

$application = new Application('DAV Manipulator', 'beta');
$application->setDispatcher($container['dispatcher']);

// AddressBook
$application->add(new Command\AddressBook\ExportCommand($container['client.factory']));
$application->add(new Command\AddressBook\ImportCommand($container['client.factory']));
$application->add(new Command\AddressBook\MergeDuplicatedContactsCommand(
    $container['client.factory'],
    $container['duplicate_finder'],
    $container['merger']
));
// Configuration
$application->add(new Command\Config\Connection\CreateCommand($container['config']));
$application->add(new Command\Config\Connection\DeleteCommand($container['config']));
$application->add(new Command\Config\Connection\ListCommand($container['config']));
$application->add(new Command\Config\Connection\TestCommand($container['client.factory']));

// Dev / debug commands
if (class_exists('Faker\Factory')) {
    $application->add(new Command\AddressBook\GenerateRandomCommand());
}

$application->run();
