#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Olidol\Console\Command\FindDuplicatesCommand;

$application = new Application();
$application->add(new FindDuplicatesCommand());
$application->run();
